pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                git branch: 'main', credentialsId: 'MyRest', url: 'https://github.com/gil-brown-a/restapi.git'
                sh "docker build . -t myrest:${currentBuild.number}"
                sh "docker run -d -p 5000:5000 myrest:${currentBuild.number}"
                sh "pytest tests.py --junitxml=reports/TEST-${currentBuild.number}.xml"
            }

            post {
                success {
                    sh '''#!/bin/bash
                            docker kill $(docker ps | grep myrest: | awk '{print $1}')
                        '''

                    junit '**/reports/TEST-*.xml'
                }
            }
        }
    }
}
